name: Compile with SourceMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: ["1.10.x", "1.11.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.sm-version }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Clone Multi Colors
        uses: actions/checkout@v2
        with:
          repository: 'Bara/Multi-Colors'
          ref: 'master'
          path: 'deps/multicolors'

      - name: Setup Multi Colors
        run: |
          MULTICOLORS_PATH=$GITHUB_WORKSPACE/deps/multicolors
          echo "MULTICOLORS_INCLUDE=$MULTICOLORS_PATH/addons/sourcemod/scripting/include" >> $GITHUB_ENV

      - name: Compile Plugins
        run: |
          for file in *.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $includePath -i $SCRIPTS_PATH/include -i $MULTICOLORS_INCLUDE $file
          done
        working-directory: ${{ env.SCRIPTS_PATH }}/
