name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package
        run: tar -czf ${{ github.ref_name }}.tar.gz $GITHUB_WORKSPACE/addons $GITHUB_WORKSPACE/LICENSE.md $GITHUB_WORKSPACE/README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.ref_name }}.tar.gz
